/**
 * Generated from Signal bookmarks by:
 *   node scripts/sync-signal-reading.mjs
 *
 * Do not edit this file by hand.
 */
export type ReadingItem = {
  id: string
  title: string
  /** ISO calendar date YYYY-MM-DD. */
  date: string
  href: string
  tag: string
  source: string
  author?: string
  blurb?: string
  imageSrc?: string
}

export const readingItems: ReadingItem[] = [
  {
    "id": "website-inspiration-brand-appart-aed86fb0",
    "title": "Website inspiration: Brand Appart",
    "date": "2026-08-18",
    "href": "https://maxibestof.one/go/zb2m3jzj3jxv4m",
    "tag": "design",
    "source": "MaxiBestOf",
    "author": "MaxiBestOf",
    "blurb": "MaxiBestOf page: https://maxibestof.one/websites/85425-brand-appart | Fonts: IBM Plex Mono, PP Neue Montreal, Youth",
    "imageSrc": "https://assets.maxibestof.one/cdn-cgi/image/width=700,quality=80,format=auto/thumbs/c2ac84c4-e641-42b9-bcac-871bd9907a6e_700.jpg"
  },
  {
    "id": "design-on-x-becoming-editorial-project-b5a664f0",
    "title": "Design on X: Becoming Editorial Project",
    "date": "2026-08-18",
    "href": "https://x.com/47thegreat_/status/2089388628627570812",
    "tag": "design",
    "source": "Recent Design X",
    "author": "47thegreat_",
    "blurb": "Curated by Recent Design from https://recent.design/.",
    "imageSrc": "https://cdn.recent.design/items/2m9qu0e/0/poster/1200.webp"
  },
  {
    "id": "design-on-x-blue-mascot-animation-840516c1",
    "title": "Design on X: Blue Mascot Animation",
    "date": "2026-08-18",
    "href": "https://x.com/mouadirl/status/2089440363660316799",
    "tag": "design",
    "source": "Recent Design X",
    "author": "mouadirl",
    "blurb": "Curated by Recent Design from https://recent.design/.",
    "imageSrc": "https://cdn.recent.design/items/zlhggk5/0/poster/1200.webp"
  },
  {
    "id": "design-on-x-status-chip-components-a80fde08",
    "title": "Design on X: Status Chip Components",
    "date": "2026-08-18",
    "href": "https://x.com/humanharshad/status/2084210162999631960",
    "tag": "design",
    "source": "Recent Design X",
    "author": "humanharshad",
    "blurb": "Curated by Recent Design from https://recent.design/.",
    "imageSrc": "https://cdn.recent.design/items/5l45bjg/0/image/c317b5baf2bc0676353f/2048.webp"
  },
  {
    "id": "21-oaks-740ce055",
    "title": "21 Oaks",
    "date": "2026-08-18",
    "href": "https://cssdesignawards.com/sites/21-oaks/49999",
    "tag": "design",
    "source": "CSS Design Awards",
    "author": "CSS Design Awards",
    "blurb": "Nominee for the CSS Design Awards Website of the Day awards.",
    "imageSrc": "https://www.cssdesignawards.com/cdasites/2026/202608/20260818035713.jpg"
  },
  {
    "id": "design-on-x-anime-fashion-character-bd53995c",
    "title": "Design on X: Anime Fashion Character",
    "date": "2026-08-18",
    "href": "https://x.com/ingi_erlingsson/status/2086558086601339039",
    "tag": "design",
    "source": "Recent Design X",
    "author": "ingi_erlingsson",
    "blurb": "Curated by Recent Design from https://recent.design/.",
    "imageSrc": "https://cdn.recent.design/items/l7l6kda/0/poster/1200.webp"
  },
  {
    "id": "value-numbering-0df7c6e0",
    "title": "Value numbering",
    "date": "2026-04-04",
    "href": "https://bernsteinbear.com/blog/value-numbering",
    "tag": "compilers",
    "source": "Max Bernstein's Blog",
    "author": "Max Bernstein's Blog",
    "blurb": "Welcome back to compiler land. Today we’re going to talk about value numbering, which is like SSA, but more. Static single assignment (SSA) gives names to values: every expression has a name, and each name corresponds to exactly one expression. It transforms programs like this: x = 0 x = x + 1 x = x + 1 where the variable x is assigned more than once in the program text, into programs like this: v0 = 0 v1 = v0 + 1 v2 = v1 + 1 where each assignment to x has been replaced with an assignment to a new fresh name. It’s great because it makes clear the differences between the two x + 1 expressions. Though they textually look similar, they compute different values. The first computes 1 and the seco"
  },
  {
    "id": "how-to-make-your-design-system-ai-ready-4dee45b9",
    "title": "How To Make Your Design System AI-Ready",
    "date": "2026-06-03",
    "href": "https://smashingmagazine.com/2026/06/how-make-design-system-ai-ready",
    "tag": "design",
    "source": "Smashing Magazine",
    "author": "hello@smashingmagazine.com (Vitaly Friedman)",
    "blurb": "Practical guide on how to reduce drifts, minimize mistakes, maintain context, and improve the quality of AI-generated prototypes. Brought to you by Design Patterns For AI Interfaces, **friendly video course on UX** and design patterns by Vitaly.",
    "imageSrc": "http://files.smashing.media/articles/how-make-design-system-ai-ready/how-make-design-system-ai-ready.jpg"
  },
  {
    "id": "design-on-x-codex-token-gambling-d5839855",
    "title": "Design on X: Codex Token Gambling",
    "date": "2026-08-18",
    "href": "https://x.com/hours/status/2088983104249852359",
    "tag": "design",
    "source": "Recent Design X",
    "author": "hours",
    "blurb": "Curated by Recent Design from https://recent.design/.",
    "imageSrc": "https://cdn.recent.design/items/ikqmj6v/0/image/e177e6323023ea895cd7/2048.webp"
  },
  {
    "id": "design-on-x-portfolio-carousel-53294da4",
    "title": "Design on X: Portfolio Carousel",
    "date": "2026-08-18",
    "href": "https://x.com/YousufSoomroDev/status/2088657289410687111",
    "tag": "design",
    "source": "Recent Design X",
    "author": "YousufSoomroDev",
    "blurb": "Curated by Recent Design from https://recent.design/.",
    "imageSrc": "https://cdn.recent.design/items/rih5dm6/0/poster/1200.webp"
  },
  {
    "id": "design-on-x-dark-card-carousel-4a7db934",
    "title": "Design on X: Dark Card Carousel",
    "date": "2026-08-18",
    "href": "https://x.com/dubkovaai/status/2088496587815211441",
    "tag": "design",
    "source": "Recent Design X",
    "author": "dubkovaai",
    "blurb": "Curated by Recent Design from https://recent.design/.",
    "imageSrc": "https://cdn.recent.design/items/e4rkkp3/0/poster/1200.webp"
  },
  {
    "id": "design-on-x-pixellated-section-18027847",
    "title": "Design on X: Pixellated Section",
    "date": "2026-08-16",
    "href": "https://x.com/mobbin/status/2087846310221430854",
    "tag": "design",
    "source": "Recent Design X",
    "author": "mobbin",
    "blurb": "Curated by Recent Design from https://recent.design/.",
    "imageSrc": "https://cdn.recent.design/items/8nhplkc/0/poster/1200.webp"
  },
  {
    "id": "design-on-x-flame-built-from-type-d0054de3",
    "title": "Design on X: Flame Built from Type",
    "date": "2026-08-16",
    "href": "https://x.com/oliverhamrin/status/2087968217700397362",
    "tag": "design",
    "source": "Recent Design X",
    "author": "oliverhamrin",
    "blurb": "Curated by Recent Design from https://recent.design/.",
    "imageSrc": "https://cdn.recent.design/items/k4ufel6/0/poster/1200.webp"
  },
  {
    "id": "design-on-x-face-icon-animation-9634eae5",
    "title": "Design on X: Face Icon Animation",
    "date": "2026-08-17",
    "href": "https://x.com/lypy/status/2088088676249075745",
    "tag": "design",
    "source": "Recent Design X",
    "author": "lypy",
    "blurb": "Curated by Recent Design from https://recent.design/.",
    "imageSrc": "https://cdn.recent.design/items/btki5jn/0/poster/1200.webp"
  },
  {
    "id": "design-on-x-rolling-dial-shader-8b2c510c",
    "title": "Design on X: Rolling Dial Shader",
    "date": "2026-08-17",
    "href": "https://x.com/Jaenam97/status/2087882106349273599",
    "tag": "design",
    "source": "Recent Design X",
    "author": "Jaenam97",
    "blurb": "Curated by Recent Design from https://recent.design/.",
    "imageSrc": "https://cdn.recent.design/items/8r9hgol/0/poster/1200.webp"
  },
  {
    "id": "design-on-x-365-days-at-vercel-e8af85eb",
    "title": "Design on X: 365 Days at Vercel",
    "date": "2026-08-14",
    "href": "https://x.com/JohnPhamous/status/2087226344564469850",
    "tag": "design",
    "source": "Recent Design X",
    "author": "JohnPhamous",
    "blurb": "Curated by Recent Design from https://recent.design/.",
    "imageSrc": "https://cdn.recent.design/items/shwd3gy/0/poster/960.webp"
  },
  {
    "id": "design-on-x-paper-design-posters-844727d8",
    "title": "Design on X: Paper Design Posters",
    "date": "2026-08-14",
    "href": "https://x.com/agusegui/status/2086947473130442930",
    "tag": "design",
    "source": "Recent Design X",
    "author": "agusegui",
    "blurb": "Curated by Recent Design from https://recent.design/.",
    "imageSrc": "https://cdn.recent.design/items/e9fgip9/0/image/e85d0b64ccff4b9e2d38/2048.webp"
  },
  {
    "id": "design-on-x-grok-bot-app-c56f9e7c",
    "title": "Design on X: Grok Bot App",
    "date": "2026-08-14",
    "href": "https://x.com/bot/status/2087224799508766921",
    "tag": "design",
    "source": "Recent Design X",
    "author": "bot",
    "blurb": "Curated by Recent Design from https://recent.design/.",
    "imageSrc": "https://cdn.recent.design/items/mgullnt/0/image/f8965efb86344359c94b/2048.webp"
  },
  {
    "id": "design-on-x-run-poster-bc82a03b",
    "title": "Design on X: Run Poster",
    "date": "2026-08-14",
    "href": "https://recent.design/i/yk9ilwf-run-poster",
    "tag": "design",
    "source": "Recent Design X",
    "author": "Recent Design",
    "blurb": "Curated by Recent Design from https://recent.design/.",
    "imageSrc": "https://cdn.recent.design/items/yk9ilwf/0/image/0b174832a05a800fc641/2048.webp"
  },
  {
    "id": "design-on-x-minimal-chess-deef8bd2",
    "title": "Design on X: Minimal Chess",
    "date": "2026-08-14",
    "href": "https://x.com/stallboerger/status/2087275432802488344",
    "tag": "design",
    "source": "Recent Design X",
    "author": "stallboerger",
    "blurb": "Curated by Recent Design from https://recent.design/.",
    "imageSrc": "https://cdn.recent.design/items/kva1lco/0/image/cb31c95eb7880f88e727/1698.webp"
  },
  {
    "id": "design-on-x-solcard-card-selection-5c1c1db9",
    "title": "Design on X: Solcard Card Selection",
    "date": "2026-08-14",
    "href": "https://x.com/designbyzipzap/status/2087202524478538080",
    "tag": "design",
    "source": "Recent Design X",
    "author": "designbyzipzap",
    "blurb": "Curated by Recent Design from https://recent.design/.",
    "imageSrc": "https://cdn.recent.design/items/1kabfx2/0/poster/1200.webp"
  },
  {
    "id": "design-on-x-spider-gwen-ar-filter-74383e5a",
    "title": "Design on X: Spider-Gwen AR Filter",
    "date": "2026-08-12",
    "href": "https://x.com/koreanoli/status/2086453504953184401",
    "tag": "design",
    "source": "Recent Design X",
    "author": "koreanoli",
    "blurb": "Curated by Recent Design from https://recent.design/.",
    "imageSrc": "https://cdn.recent.design/items/gthd82l/0/poster/1200.webp"
  },
  {
    "id": "design-on-x-chess-app-icon-bc7c25f2",
    "title": "Design on X: Chess App Icon",
    "date": "2026-08-13",
    "href": "https://x.com/avstorm/status/2086880196804714810",
    "tag": "design",
    "source": "Recent Design X",
    "author": "avstorm",
    "blurb": "Curated by Recent Design from https://recent.design/.",
    "imageSrc": "https://cdn.recent.design/items/qlwb6b3/0/image/bc62b9c10bcc81916e5b/1682.webp"
  },
  {
    "id": "openchamber-an-agentic-development-environment-bfda1df5",
    "title": "OpenChamber: An Agentic Development Environment",
    "date": "2026-08-09",
    "href": "https://openchamber.dev",
    "tag": "design",
    "source": "Hacker News",
    "author": "hexomancer",
    "blurb": "Article URL: https://openchamber.dev/ Comments URL: https://news.ycombinator.com/item?id=49233448 Points: 158 # Comments: 76"
  },
  {
    "id": "design-on-x-cloudflare-workers-animation-ac2fd1a5",
    "title": "Design on X: Cloudflare Workers Animation",
    "date": "2026-08-11",
    "href": "https://x.com/tjcages/status/2085832589206814850",
    "tag": "design",
    "source": "Recent Design X",
    "author": "tjcages",
    "blurb": "Curated by Recent Design from https://recent.design/.",
    "imageSrc": "https://cdn.recent.design/items/t41jbsu/0/poster/1200.webp"
  },
  {
    "id": "vitali87-code-graph-rag-ad4fec82",
    "title": "vitali87/code-graph-rag",
    "date": "2026-08-09",
    "href": "https://github.com/vitali87/code-graph-rag",
    "tag": "ai",
    "source": "GitHub Trending",
    "author": "vitali87",
    "blurb": "The ultimate RAG for your monorepo. Query, understand, and edit multi-language codebases with the power of AI and knowledge graphs"
  },
  {
    "id": "design-on-x-mist-effect-1ca440fe",
    "title": "Design on X: Mist Effect",
    "date": "2026-08-12",
    "href": "https://x.com/jiholimm/status/2086452439520325636",
    "tag": "design",
    "source": "Recent Design X",
    "author": "jiholimm",
    "blurb": "Curated by Recent Design from https://recent.design/.",
    "imageSrc": "https://cdn.recent.design/items/3pa6ojq/0/poster/1200.webp"
  },
  {
    "id": "design-on-x-cards-carousel-c494cfe5",
    "title": "Design on X: Cards Carousel",
    "date": "2026-08-11",
    "href": "https://x.com/iliazolotukhin/status/2086109742363971834",
    "tag": "design",
    "source": "Recent Design X",
    "author": "iliazolotukhin",
    "blurb": "Curated by Recent Design from https://recent.design/.",
    "imageSrc": "https://cdn.recent.design/items/2ugpqkg/0/poster/1199.webp"
  },
  {
    "id": "design-on-x-age-progression-slider-e1aba520",
    "title": "Design on X: Age Progression Slider",
    "date": "2026-08-11",
    "href": "https://x.com/AdityaSur11/status/2086384491040317846",
    "tag": "design",
    "source": "Recent Design X",
    "author": "AdityaSur11",
    "blurb": "Curated by Recent Design from https://recent.design/.",
    "imageSrc": "https://cdn.recent.design/items/uy89u6i/0/poster/1200.webp"
  },
  {
    "id": "website-inspiration-specimen-studio-61e57b22",
    "title": "Website inspiration: Specimen Studio",
    "date": "2026-08-18",
    "href": "https://maxibestof.one/go/wvdmm8zgbdbj8n",
    "tag": "design",
    "source": "MaxiBestOf",
    "author": "MaxiBestOf",
    "blurb": "MaxiBestOf page: https://maxibestof.one/websites/85117-specimen-studio | Fonts: Helvetica Neue, PP Editorial Old",
    "imageSrc": "https://assets.maxibestof.one/cdn-cgi/image/width=700,quality=80,format=auto/thumbs/d62da03d-ed46-407e-9ce5-215c10d2b405_700.jpg"
  },
  {
    "id": "website-inspiration-house-of-honey-6a6d4b5c",
    "title": "Website inspiration: House Of Honey",
    "date": "2026-08-18",
    "href": "https://maxibestof.one/go/2b3ng97gygd7e7",
    "tag": "design",
    "source": "MaxiBestOf",
    "author": "MaxiBestOf",
    "blurb": "MaxiBestOf page: https://maxibestof.one/websites/85624-house-of-honey | Fonts: House of HoneyCanora Test Frente, Neue Haas Grotesk, Noe Text",
    "imageSrc": "https://assets.maxibestof.one/cdn-cgi/image/width=700,quality=80,format=auto/thumbs/f0c866cb-32a3-4e53-9b12-dac197635f13_700.jpg"
  },
  {
    "id": "design-on-x-heraldic-lion-mark-4249edec",
    "title": "Design on X: Heraldic Lion Mark",
    "date": "2026-08-10",
    "href": "https://x.com/koendesigns/status/2085717880252076187",
    "tag": "design",
    "source": "Recent Design X",
    "author": "koendesigns",
    "blurb": "Curated by Recent Design from https://recent.design/.",
    "imageSrc": "https://cdn.recent.design/items/ot50y4o/0/image/ffb115e22a8d6ceb2c5d/1500.webp"
  },
  {
    "id": "design-on-x-asmr-portfolio-interactions-649ccb2f",
    "title": "Design on X: ASMR Portfolio Interactions",
    "date": "2026-08-10",
    "href": "https://x.com/YousufSoomroDev/status/2085800942633664613",
    "tag": "design",
    "source": "Recent Design X",
    "author": "YousufSoomroDev",
    "blurb": "Curated by Recent Design from https://recent.design/.",
    "imageSrc": "https://cdn.recent.design/items/8sy6r7f/0/poster/1200.webp"
  },
  {
    "id": "design-on-x-color-badge-system-f2544ae8",
    "title": "Design on X: Color Badge System",
    "date": "2026-08-11",
    "href": "https://x.com/colmtuite/status/2073404064168034749",
    "tag": "design",
    "source": "Recent Design X",
    "author": "colmtuite",
    "blurb": "Curated by Recent Design from https://recent.design/.",
    "imageSrc": "https://cdn.recent.design/items/u6rejp1/0/image/38c37e6a5df12a9e94ff/830.webp"
  },
  {
    "id": "we-have-inherited-the-surfaces-of-decadence-luxury-excess-artifi-06896f4f",
    "title": "“We have inherited the surfaces of decadence — luxury, excess, artifice, bodily display — but have surrendered the fin de siècle’s commitment to pleasure”",
    "date": "2026-08-08",
    "href": "https://theguardian.com/us-news/ng-interactive/2026/jul/26/age-of-decadence-pleasure-ai",
    "tag": "ux",
    "source": "Arts & Letters Daily",
    "author": "Arts & Letters Daily",
    "blurb": "“We have inherited the surfaces of decadence — luxury, excess, artifice, bodily display — but have surrendered the fin de siècle’s commitment to pleasure”"
  },
  {
    "id": "ai-poses-a-moral-hazard-but-it-may-also-render-unintelligible-cu-4d9781a8",
    "title": "AI poses a moral hazard, but it may also render unintelligible cultural concepts like merit, authenticity, expertise, and deliberation",
    "date": "2026-08-08",
    "href": "https://thepointmag.com/letter/on-radical-preservation",
    "tag": "ideas",
    "source": "Arts & Letters Daily",
    "author": "Arts & Letters Daily",
    "blurb": "AI poses a moral hazard, but it may also render unintelligible cultural concepts like merit, authenticity, expertise, and deliberation"
  },
  {
    "id": "design-on-x-igochi-studio-website-a659aefc",
    "title": "Design on X: Igochi Studio Website",
    "date": "2026-08-07",
    "href": "https://x.com/arushiupmanyu/status/2077767367174799579",
    "tag": "design",
    "source": "Recent Design X",
    "author": "arushiupmanyu",
    "blurb": "Curated by Recent Design from https://recent.design/.",
    "imageSrc": "https://cdn.recent.design/items/h4q8s9i/0/poster/1200.webp"
  },
  {
    "id": "design-on-x-shader-glass-buttons-d948a45e",
    "title": "Design on X: Shader Glass Buttons",
    "date": "2026-08-07",
    "href": "https://x.com/tranmautritam/status/2079207566526259654",
    "tag": "design",
    "source": "Recent Design X",
    "author": "tranmautritam",
    "blurb": "Curated by Recent Design from https://recent.design/.",
    "imageSrc": "https://cdn.recent.design/items/b5tfl45/0/poster/960.webp"
  },
  {
    "id": "design-on-x-ai-motion-study-e5140eb8",
    "title": "Design on X: AI Motion Study",
    "date": "2026-08-07",
    "href": "https://x.com/__causasui/status/2042632462548050088",
    "tag": "design",
    "source": "Recent Design X",
    "author": "__causasui",
    "blurb": "Curated by Recent Design from https://recent.design/.",
    "imageSrc": "https://cdn.recent.design/items/oxcci37/0/poster/700.webp"
  },
  {
    "id": "art-scout-f0dc4934",
    "title": "Art Scout",
    "date": "2026-08-11",
    "href": "https://cssdesignawards.com/sites/art-scout/49931",
    "tag": "design",
    "source": "CSS Design Awards",
    "author": "CSS Design Awards",
    "blurb": "Nominee for the CSS Design Awards Website of the Day awards.",
    "imageSrc": "https://www.cssdesignawards.com/cdasites/2026/202608/20260806125047.jpg"
  },
  {
    "id": "tencentcloud-tencentdb-agent-memory-b599dd2f",
    "title": "TencentCloud/TencentDB-Agent-Memory",
    "date": "2026-08-06",
    "href": "https://github.com/TencentCloud/TencentDB-Agent-Memory",
    "tag": "design",
    "source": "GitHub Trending",
    "author": "TencentCloud",
    "blurb": "TencentDB Agent Memory is a team-level memory hub for AI Agents — turning conversations, docs, and code into four reusable memory assets (Chat Memory, Skill, LLM-Wiki, Code-Graph) that are governed, shared, and equipped across agents and frameworks."
  },
  {
    "id": "mattpocock-skills-637c9910",
    "title": "mattpocock/skills",
    "date": "2026-08-06",
    "href": "https://github.com/mattpocock/skills",
    "tag": "ai",
    "source": "GitHub Trending",
    "author": "mattpocock",
    "blurb": "Skills for Real Engineers. Straight from my .agents directory."
  },
  {
    "id": "design-on-x-node-connection-interaction-9c89eb6d",
    "title": "Design on X: Node Connection Interaction",
    "date": "2026-08-07",
    "href": "https://x.com/arknow91/status/2085236928354349542",
    "tag": "design",
    "source": "Recent Design X",
    "author": "arknow91",
    "blurb": "Curated by Recent Design from https://recent.design/.",
    "imageSrc": "https://cdn.recent.design/items/x2hewj5/0/poster/1200.webp"
  },
  {
    "id": "design-on-x-journal-app-detail-transition-77f98633",
    "title": "Design on X: Journal App Detail Transition",
    "date": "2026-08-07",
    "href": "https://x.com/JaejinBong/status/2085379870842912772",
    "tag": "design",
    "source": "Recent Design X",
    "author": "JaejinBong",
    "blurb": "Curated by Recent Design from https://recent.design/.",
    "imageSrc": "https://cdn.recent.design/items/j749047/0/poster/1200.webp"
  },
  {
    "id": "human-like-neural-nets-by-catapulting-0f434aa6",
    "title": "Human-like Neural Nets by Catapulting",
    "date": "2026-07-18",
    "href": "https://gwern.net/llm-catapult",
    "tag": "ai",
    "source": "Lobsters",
    "author": "gwern.net via sunflowerseastar"
  },
  {
    "id": "you-could-have-come-up-with-kimi-delta-attention-4cdfa332",
    "title": "You Could Have Come Up With Kimi Delta Attention",
    "date": "2026-07-28",
    "href": "https://blog.doubleword.ai/you-could-have-come-up-with-kimi-delta-attention",
    "tag": "ai",
    "source": "Lobsters",
    "author": "blog.doubleword.ai via mitsuhiko"
  },
  {
    "id": "why-we-write-our-own-c-and-c-inference-engines-f907581a",
    "title": "Why we write our own C and C++ inference engines",
    "date": "2026-07-31",
    "href": "https://localai.io/blog/why-we-write-our-own-engines",
    "tag": "c",
    "source": "Lobsters",
    "author": "localai.io via eatonphil"
  },
  {
    "id": "openclaw-and-ollama-in-agentic-ai-toward-fully-autonomous-and-sc-e2ebf215",
    "title": "OpenClaw and Ollama in Agentic AI: Toward Fully Autonomous and Scalable AI Agent Systems",
    "date": "2026-08-03",
    "href": "https://arxiv.org/abs/2607.28629",
    "tag": "ux",
    "source": "arXiv Computer Science",
    "author": "Konstantinos I. Roumeliotis, Ranjan Sapkota",
    "blurb": "arXiv:2607.28629v1 Announce Type: new Abstract: The rapid transition from reactive large language models (LLMs) to persistent, action-capable systems has exposed critical gaps in the architectural understanding of Agentic AI, particularly in separating inference, orchestration, and execution layers for autonomous AI agents. Despite recent advances, unified frameworks for designing and evaluating full-stack agentic systems remain limited. This paper presents a comprehensive, layered architecture for Agentic AI, outlining the evolution from reactive LLM interfaces to persistent, goal-driven autonomous AI agents with memory, planning, and continuous execution. We analyze OpenClaw and Ollama as"
  },
  {
    "id": "ai-learns-the-dark-art-of-rf-chip-design-0ab3d756",
    "title": "AI Learns the \"Dark Art\" of RF Chip Design",
    "date": "2026-06-27",
    "href": "https://spectrum.ieee.org/ai-radio-chip-design",
    "tag": "ai",
    "source": "Lobsters",
    "author": "spectrum.ieee.org via Yogthos",
    "blurb": "Article URL: https://spectrum.ieee.org/ai-radio-chip-design Comments URL: https://news.ycombinator.com/item?id=48660021 Points: 249 # Comments: 161"
  },
  {
    "id": "design-on-x-text-selection-flowers-f4c94c8e",
    "title": "Design on X: Text Selection Flowers",
    "date": "2026-08-06",
    "href": "https://x.com/omer_assa/status/2083862523640496179",
    "tag": "design",
    "source": "Recent Design X",
    "author": "omer_assa",
    "blurb": "Curated by Recent Design from https://recent.design/.",
    "imageSrc": "https://cdn.recent.design/items/fyvqnng/0/poster/822.webp"
  },
  {
    "id": "design-on-x-the-roman-sage-11384bcf",
    "title": "Design on X: The Roman Sage",
    "date": "2026-08-07",
    "href": "https://x.com/its_sslvr/status/2084142215409074503",
    "tag": "design",
    "source": "Recent Design X",
    "author": "its_sslvr",
    "blurb": "Curated by Recent Design from https://recent.design/.",
    "imageSrc": "https://cdn.recent.design/items/7msp6ij/0/poster/1200.webp"
  },
  {
    "id": "design-on-x-rare-arts-collection-2ea24046",
    "title": "Design on X: Rare Arts Collection",
    "date": "2026-08-07",
    "href": "https://x.com/lineofakc/status/2084171239963099534",
    "tag": "design",
    "source": "Recent Design X",
    "author": "lineofakc",
    "blurb": "Curated by Recent Design from https://recent.design/.",
    "imageSrc": "https://cdn.recent.design/items/0wjvheb/0/poster/1200.webp"
  },
  {
    "id": "don-t-be-a-meat-proxy-52cfd2a8",
    "title": "Don't be a meat proxy",
    "date": "2026-08-03",
    "href": "https://gruhn.me/blog/2026-08-03",
    "tag": "design",
    "source": "Lobsters",
    "author": "gruhn.me via antonmedv",
    "blurb": "Article URL: https://gruhn.me/blog/2026-08-03/ Comments URL: https://news.ycombinator.com/item?id=49151933 Points: 699 # Comments: 302"
  },
  {
    "id": "the-absurdity-of-albert-camus-d13c9d80",
    "title": "The Absurdity of Albert Camus",
    "date": "2026-07-30",
    "href": "https://historytoday.com/archive/portrait-author-historian/absurdity-albert-camus",
    "tag": "Hacker News",
    "source": "Hacker News",
    "author": "apollinaire",
    "blurb": "Article URL: https://www.historytoday.com/archive/portrait-author-historian/absurdity-albert-camus Comments URL: https://news.ycombinator.com/item?id=49117089 Points: 133 # Comments: 57"
  },
  {
    "id": "design-on-x-apple-logo-doodles-46e65774",
    "title": "Design on X: Apple Logo Doodles",
    "date": "2026-08-01",
    "href": "https://x.com/avstorm/status/2082726291820707943",
    "tag": "design",
    "source": "Recent Design X",
    "author": "avstorm",
    "blurb": "Curated by Recent Design from https://recent.design/.",
    "imageSrc": "https://cdn.recent.design/items/0hsb3te/0/image/2478c5c0931aeff9c80d/1600.webp"
  },
  {
    "id": "design-on-x-recursive-surface-erosion-4458f50a",
    "title": "Design on X: Recursive Surface Erosion",
    "date": "2026-08-03",
    "href": "https://x.com/hal_chemy/status/2083003699966689564",
    "tag": "design",
    "source": "Recent Design X",
    "author": "hal_chemy",
    "blurb": "Curated by Recent Design from https://recent.design/.",
    "imageSrc": "https://cdn.recent.design/items/vuzcu2u/0/poster.jpg"
  },
  {
    "id": "citrolabs-ego-lite-dbbcb182",
    "title": "citrolabs/ego-lite",
    "date": "2026-07-31",
    "href": "https://github.com/citrolabs/ego-lite",
    "tag": "design",
    "source": "GitHub Trending",
    "author": "citrolabs",
    "blurb": "The fastest browser for AI agents to run browser automation, built for sharing your logged-in browser state with your AI agents, like Codex or Claude Code, without disturbing you. Zero cost, zero config."
  },
  {
    "id": "block-buzz-59122470",
    "title": "block/buzz",
    "date": "2026-07-31",
    "href": "https://github.com/block/buzz",
    "tag": "github",
    "source": "GitHub Trending",
    "author": "block",
    "blurb": "A hive mind communication platform"
  },
  {
    "id": "design-on-x-gradient-motion-study-f2188d7f",
    "title": "Design on X: Gradient Motion Study",
    "date": "2026-08-03",
    "href": "https://recent.design/i/htqifu7-gradient-motion-study",
    "tag": "design",
    "source": "Recent Design X",
    "author": "Recent Design",
    "blurb": "Curated by Recent Design from https://recent.design/.",
    "imageSrc": "https://cdn.recent.design/items/htqifu7/0/poster.jpg"
  },
  {
    "id": "elevators-d391748e",
    "title": "Elevators",
    "date": "2026-08-01",
    "href": "https://john.fun/elevators",
    "tag": "design",
    "source": "Lobsters",
    "author": "john.fun via markerz",
    "blurb": "Article URL: https://john.fun/elevators Comments URL: https://news.ycombinator.com/item?id=49124218 Points: 1333 # Comments: 326"
  }
]
